name: Android/Ios Release

# 1
on:
  # 2
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 
    name: Build & Release
    runs-on: macos-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.0.0"
          channel: 'stable'
          architecture: x64
          cache: true
      # 12
      - name: Get dependencies
        run: flutter pub get
      
      # Run tests
      #- name: Run Flutter tests
      #  run: flutter test
      # Generate Apk
      - name: Generating APK
        run: flutter build apk --release --split-per-abi


      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.7
          token: ${{ secrets.TOKEN }}